name: Atualizar Ocorrencias

on:
  schedule:
    # Executa a cada 5 minutos de forma automatica
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  coletar-e-atualizar:
    runs-on: ubuntu-24.04

    steps:
      - name: Baixar arquivos do repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Executar coletor.py
        run: python coletor.py

      - name: Salvar e publicar atualizacoes
        run: |
          git config --global user.name "Robo Alerta"
          git config --global user.email "bot@github.actions"
          git add ocorrencias.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Atualizacao continua (5 min)" && git push)
